repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.1
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_tfsec
      args:
        - --args=--format json

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: check-json
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: check-case-conflict
    - id: mixed-line-ending
      args:
      - --fix=lf

- repo: https://github.com/timothycrosley/isort
  rev: 5.11.5
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3
